server:
  port: 8088
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/bitmask
    username: root
    password: n0p0d
  jpa:
    hibernate:
      ddl-auto: validate